### ISSUE TITLE
Action Fails because branch=null

### ISSUE THREAD

**Issue by Beatzoid** [humbletim/setup-vulkan-sdk#2] opened 2021-06-16 18:14 UTC
I'm trying to use this action on [this](https://github.com/Beatzoid/kohi) repo, however, the CI is failing because it logs that `BRANCH=null`. I've tried specifying and not specifying the version, but neither one fixed the issue.
Links to the CI Logs:

[Windows without specifying the version](https://github.com/Beatzoid/kohi/actions/runs/943647341)
[Linux without specifying the version](https://github.com/Beatzoid/kohi/actions/runs/943647342)
[Windows with specifying the version](https://github.com/Beatzoid/kohi/actions/runs/943652823)
[Linux with specifying the version](https://github.com/Beatzoid/kohi/actions/runs/943652824)

**Comment by humbletim** [comment] 2021-06-18 19:20
confirmed / investigating (initial guess is that the vulkan sdk web service being used may have changed again)

**Comment by Beatzoid** [comment] 2021-06-18 20:07
Sounds good, thanks!

**Comment by humbletim** [comment] 2021-06-18 20:10
OK it's definitely an issue with the SDK service (though only seems to be affecting the very latest release (`latest`/`1.2.176.1`)). 

I've submitted a bug report here: https://vulkan.lunarg.com/issue/view/60ccf8375df11202e4e0cf42

If looking for a temporary workaround then it looks like specifying _sdk just prior to latest_ (`1.2.170.0`) still works.

**Comment by Beatzoid** [comment] 2021-06-18 20:17
Alright, thank you so much!

**Comment by Beatzoid** [comment] 2021-06-18 20:19
I tried specifying `1.2.170.0`` as the version but it failed. [Logs](https://github.com/Beatzoid/kohi/runs/2861546908)

**Comment by humbletim** [comment] 2021-07-06 01:41
Looks like the sidestream LunarG webservice issue has been resolved -- marking this as closed however please feel free to ping me if further help is needed setting things up later.

Note: as of v1.0.2 this addon now supports using an *exact Vulkan SDK internal branch name* like `sdk-x.y.z` -- which might be more reliable since it provides a cloneable commit point directly (avoiding any need to depend on SDK webservices).

**Closed as completed by humbletim** 2021-07-06 01:41 UTC
Labels: bug
